language: node_js
node_js:
- 9
script:
- npm run build
notifications:
  email:
    on_failure: change
before_deploy:
  - pip install --user awscli
deploy:
  provider: script
  script: bash ./s3_sync.sh snuev.kr
  skip_cleanup: true
cache:
  yarn: true
  directories:
  - node_modules
