version: '3'
services:
  app:
    build: .
    command: yarn start
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/src/app'
      - 'node_modules:/usr/src/app/node_modules'
    environment:
      - API_HOST=http://lvh.me:3001
    env_file: .env
volumes:
  node_modules:
